Tutorial char enc
w3c/i18n-drafts pull request #376
Opened 2022-05-30 15:31 UTC by brandelune

2022-05-30 17:03 UTC, r12a requested changes

2022-05-30 17:03 UTC, r12a commented on tutorials/language-decl/index.fr.html
> +<meta name="description" content="Tutoriel W3C i18n : Comment déclarer et utiliser les langues dans les fichiers XHTML et HTML" />
Looks like you're using nbsp.  The recent trend is to use U+202F NARROW NO-BREAK SPACE for French punctuation.  What do you think?

2022-05-30 17:03 UTC, r12a commented on tutorials/language-decl/index.fr.html
> +<script>
Well spotted!

2022-05-30 17:03 UTC, r12a commented on tutorials/language-decl/index.fr.html
> +	<section>
Hmm. Another thing i missed while updating the templates: the id should always be on the section tag.  Would you mind fixing it for the French (i'll fix the other languages).

2022-05-30 17:03 UTC, r12a commented on tutorials/language-decl/index.fr.html
> +<h2 id="quicksummary">En bref</h2>
(This quicksummary id is ok on the h2 tag.)

2022-05-30 17:03 UTC, r12a commented on tutorials/tutorial-char-enc/index.fr.html
> +    <li><a class="print" href="/International/questions/qa-what-is-encoding.fr">Les encodages de caractères pour débutants</a></li>
No .fr extensions, please! The links are content negotiated.  This applies to several edits. Please change them back, thanks.

2022-05-30 17:03 UTC, r12a commented on tutorials/tutorial-char-enc/index.fr.html
> +        <li><a href="https://www.w3.org/International/techniques/authoring-html.en?open=charset#charset">Caractères</a></li>
We should drop the "https://www.w3.org" and the ".en".

2022-06-01 04:08 UTC, brandelune commented on tutorials/language-decl/index.fr.html
> +<meta name="description" content="Tutoriel W3C i18n : Comment déclarer et utiliser les langues dans les fichiers XHTML et HTML" />
It's not trivial to type even on a mac keyboard so I usually use NBSP. But I'll batch replace the thing and will commit again.

2022-06-01 04:09 UTC, brandelune commented on tutorials/language-decl/index.fr.html
> +<script>
OmegaT does that automatically. It takes the structure of the original and will just fill it with the translated texts. So you have to thank OmegaT :-)

2022-06-01 04:10 UTC, brandelune commented on tutorials/language-decl/index.fr.html
> +	<section>
ok

2022-06-01 04:11 UTC, brandelune commented on tutorials/language-decl/index.fr.html
> +<h2 id="quicksummary">En bref</h2>
Nothing to do then ?

2022-06-01 04:12 UTC, brandelune commented on tutorials/tutorial-char-enc/index.fr.html
> +    <li><a class="print" href="/International/questions/qa-what-is-encoding.fr">Les encodages de caractères pour débutants</a></li>
I'm on it.

2022-06-02 08:02 UTC, closed without merging