Adjust the Chinese font stack
w3c/i18n-drafts pull request #389
Opened 2022-06-07 01:39 UTC by xfq

Latin fonts are placed before Chinese fonts because some Chinese fonts have ugly English/Cyrillic/Greek glyphs.

For more background, see https://github.com/w3c/clreq/issues/408#issuecomment-1103501409

2022-06-07 07:41 UTC, r12a requested changes
I think the @font-face declarations need to appear at the very beginning of the CSS style sheet, otherwise they don't work.

2022-06-07 07:44 UTC, r12a commented
ie. before the declaration for the body tag.

2022-06-08 01:58 UTC, xfq commented
Done.

2022-06-08 10:36 UTC, r12a approved these changes

2022-06-08 11:26 UTC, merged

2022-06-08 11:27 UTC, xfq commented
Do we need to upload these files to the CVS server?

2022-06-13 10:57 UTC, r12a commented
Already done.