Update the titles of the techniques page
w3c/i18n-drafts pull request #550
Opened 2023-10-11 04:51 UTC by xfq

2023-10-11 14:02 UTC, r12a commented
LGTM as long as it's always clear from the link or the styling that this is the title of a document.

2023-10-11 16:29 UTC, aphillips requested changes
See comment about titlecase

2023-10-11 16:29 UTC, aphillips commented on article-list/articlelist.en.html
> +<p>You can also find resources using the page <a href="https://www.w3.org/International/techniques/authoring-html" class="external text" title="https://www.w3.org/International/techniques/authoring-h
I know that Richard has slightly different preferences, but I think we should discuss them (and add the results to our style guide for posterity).

I tend to think that we should use "Elements of Style" title case, which capitalizes most words (except articles and prepositions). That would make this document:

> Internationalization Techniques: Authoring Web Pages

Separately I would note that W3C tends to capitalize Web, which makes "Authoring Web pages" look odd.

2023-10-12 11:44 UTC, r12a commented on article-list/articlelist.en.html
> +<p>You can also find resources using the page <a href="https://www.w3.org/International/techniques/authoring-html" class="external text" title="https://www.w3.org/International/techniques/authoring-h
In fact, i think it was this year, or maybe last, W3C Comm team issued guidance that said that the word 'web' would mostly be lowercase, and only uppercase when referring to '_the_ Web'.  Terms like 'web page' would be lowercase.

@aphillips i had similar thoughts to you, but i'm not sure whether you are advocating that the headings themselves should be capitalised, or just the link text.  I would like to maintain our downstyle approach for the headings themselves, but am inclined to support having capitalised link text.

2023-10-13 05:10 UTC, xfq commented on article-list/articlelist.en.html
> +<p>You can also find resources using the page <a href="https://www.w3.org/International/techniques/authoring-html" class="external text" title="https://www.w3.org/International/techniques/authoring-h
I'm OK with either one, as long as it's consistent.

See also:

* https://blog.ap.org/products-and-services/ready-to-lowercase-internet-and-web
* https://w3c.studio24.net/docs/proposed-site-map-v2/#sentence-case-for-navigation-labels-and-headings

2024-05-17 02:48 UTC, merged

2024-05-17 02:49 UTC, xfq commented
Per 2024-05-16 teleconference discussion, merging this PR as is.