Move the tools page to GitHub
w3c/i18n-drafts pull request #587
Opened 2024-06-12 01:21 UTC by xfq

Move https://www.w3.org/International/tools from CVS to GitHub.

After merging this, I'll raise another PR to update the content of this page.

2024-06-12 09:40 UTC, r12a commented
Nowadays, i have a bunch of other tools/apps/pages which may be worth mentioning here, such as the Font Lister, Grapheme Cluster Segmenter, etc.  You might want to scan https://r12a.github.io/scripts/ and https://r12a.github.io/applist for potential candidates.

2024-06-12 09:44 UTC, r12a requested changes

2024-06-12 09:44 UTC, r12a commented on pages/tools.en.html
> +          <p><a href="https://r12a.github.io/apps/conversion/">Unicode code converter</a><br>
This app is now available at https://r12a.github.io/app-conversion/

2024-06-12 09:44 UTC, r12a commented on pages/tools.en.html
> +          <p><a href="https://r12a.github.io/apps/encodings/">Encoding converter</a><br>
This app is now available at https://r12a.github.io/app-encodings/

2024-06-12 09:44 UTC, r12a commented on pages/tools.en.html
> +          <p><a href="https://r12a.github.io/apps/listcharacters/">List characters tool</a><br>
This app is now available at https://r12a.github.io/app-listcharacters/

2024-06-12 09:44 UTC, r12a commented on pages/tools.en.html
> +				<p><a href="http://r12a.github.io/apps/subtags/">IANA Language Subtag Registry search tool</a><br>
This app is now available at https://r12a.github.io/app-subtags/

2024-06-12 09:44 UTC, r12a commented on pages/tools.en.html
> +      <p><a href="http://r12a.github.io/apps/counterconverter/">Counter styles converter</a><br>
This app is now available at https://r12a.github.io/app-counters/

2024-06-12 09:44 UTC, r12a commented on pages/tools.en.html
> +				pickers display the characters that are used for a range of languages, and allow you to compose one or more words by clicking on characters. The
I suggest to replace this sentence with:
> The pickers allow you to produce, analyse and manipulate runs of text for a given language or script.

2024-06-12 09:44 UTC, r12a commented on pages/tools.en.html
> +				list of scripts supported includes Arabic, Armenian, Bengali, Devanagari, Egyptian Hieroglyphs, Ethiopic, Gujarati, Gurmukhi, Hebrew, Khmer, IPA, Lao, Latin, Lisu, Malayalam, Myanmar, Runic, Tami
The first sentence is long out of date.  I suggest to replace with:

> The pickers support well over 100 orthographies in over 90 different scripts.  They are particularly useful for...

2024-06-12 09:44 UTC, r12a commented on pages/tools.en.html
> +<script type="text/javascript">completePage()</script>
we should remove type="text/javascript"

2024-06-13 05:16 UTC, xfq commented
As I said in https://github.com/w3c/i18n-drafts/pull/587#issue-2347569473 , I plan to update the content of this page ***after*** merging this PR, as it will be clearer what has been updated.

2024-06-21 05:51 UTC, merged